### ISSUE TITLE
I get "Check your internet connection!" 

### ISSUE THREAD

**Issue by affane1** [iamsuatzengin/image-generator-openAi#1]
Even after setting my own private API key in the source code, I keep getting "Check your internet connection!" after clicking on Next.

One thing I have a doubt about is the Channel ID. I left that field empty as I didn't what it referred to or where I could get it. Could it be responsible for that error message ?

**Comment by iamsuatzengin** [comment]
You must use token with Bearer. like this:  -->  **`"Bearer YOUR_TOKEN"`**. 

I think it must be solved. The message ( "Check your internet connection!") when an error occur had better  change with "throwable.getLocalizedMessage()".

**Comment by affane1** [comment]
@iamsuatzengin 

Using throwable.getLocalizedMessage() worked more accurately as you described, returning a message of "HTTP 401" in my case.

Using the format "Bearer YOUR_TOKEN" also worked.

Thanks for your answer :)
